ci:
  autoupdate_schedule: quarterly
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.5
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/jazzband/pip-tools
    rev: 7.4.1
    hooks:
      - id: pip-compile
        name: pip-compile requirements.in
        files: ^requirements\.(in|txt)$
      - id: pip-compile
        name: pip-compile requirements_dev.in
        files: ^requirements(_dev)?\.(in|txt)$
        args: [requirements_dev.in]

