[tool.ruff]
line-length = 119
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN", "COM", "EM",
  # https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
  "W191", "E501", "D206", "Q000", "Q001", "Q002", "Q003", "ISC001",
  "D203", "D212",  # incompatible rules
  "D200",  # documentation preferences
  "C901", "PLR0912",  # complexity preferences
  "D100", "D103", "D400", "D415",
  "S113",  # requests timeout
  "S603",  # subprocess
]
