[tool.ruff]
line-length = 119
target-version = "py311"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "ANN", "COM", "EM",
  "D203", "D212",  # incompatible rules
  "D200",  # documentation preferences
  "C901", "PLR0912",  # complexity preferences
  "D100", "D103",
]
